export const SKILL_DATA = [
  { name: "Next.js",      slug: "nextdotjs",          col: "e2e8f0", short: "React framework for production" },
  { name: "React",        slug: "react",               col: "61dafb", short: "UI component library" },
  { name: "Node.js",      slug: "nodedotjs",           col: "6cc24a", short: "JavaScript server runtime" },
  { name: "FastAPI",      slug: "fastapi",             col: "009688", short: "High-performance Python APIs" },
  { name: "AWS",          slug: "amazonwebservices",   col: "ff9900", short: "Cloud infrastructure & services" },
  { name: "Python",       slug: "python",              col: "4584b6", short: "Scripting and backend logic" },
  { name: "TypeScript",   slug: "typescript",          col: "3178c6", short: "Type-safe JavaScript" },
  { name: "PostgreSQL",   slug: "postgresql",          col: "699eca", short: "Relational database" },
  { name: "Docker",       slug: "docker",              col: "2496ed", short: "Container platform" },
  { name: "Tailwind CSS", slug: "tailwindcss",         col: "38bdf8", short: "Utility-first styling" },
];

export const PROJECTS = [
  {
    id: 0,
    name: "Ascend",
    tagline: "Productivity & goal tracking app",
    logo: "/ascendLogo.png",
    platforms: ["Web", "Android"],
    desc: "Full-stack productivity platform with hierarchical goal tracking, calendar-based task scheduling, vision boards, rich note-taking, and affirmation audio playback.\n\nServerless Python/FastAPI backend on AWS Lambda with async PostgreSQL via SQLAlchemy and Alembic migrations. Multi-method auth: Google OAuth, JWT sessions, bcrypt password hashing, and email OTP verification.\n\nAWS S3 for vision board image uploads and affirmation audio storage. Frontend deployed on Vercel.",
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "FastAPI", "Python", "PostgreSQL", "AWS Lambda", "S3", "Zustand", "TanStack Query"],
    techGroups: [
      { label: "Frontend", items: ["Next.js", "TypeScript", "Tailwind CSS v4", "Zustand", "TanStack Query", "Radix UI"] },
      { label: "Backend", items: ["FastAPI", "Python", "SQLAlchemy", "Alembic"] },
      { label: "Infrastructure", items: ["AWS Lambda", "AWS S3", "Supabase", "PostgreSQL", "Vercel"] },
      { label: "Auth", items: ["Google OAuth", "JWT", "bcrypt", "Email OTP"] },
    ],
    year: "2024",
    gh: "#",
    live: "https://ascend.binishanaga.com.np/",
    mobile: "http://downloads.binishanaga.com.np/ascend.apk",
  },
  {
    id: 1,
    name: "NEPSE Portfolio Tracker",
    tagline: "Stock analytics for Nepal investors",
    logo: "/nepselogo.png",
    desc: "Portfolio analytics dashboard for Nepal Stock Exchange (NEPSE) investors. Investors upload their TMS Trade Book (Excel) and MeroShare CDSC Holdings (CSV) to get an instant breakdown of their portfolio. Implemented a serverless backend using AWS Lambda, deployed the frontend on Vercel.",
    tech: ["React", "FastAPI", "AWS Lambda", "Recharts", "Docker", "Tailwind CSS"],
    year: "2024",
    gh: "#",
    live: "https://stock-portfolio-frontend-rouge.vercel.app/",
  },
  {
    id: 2,
    name: "Sudoku",
    tagline: "puzzle game ",
    logo: "/sudoku.png",
    platforms: ["Web", "Android"],
    images: undefined as string[] | undefined,
    video: undefined as string | undefined,
    desc: "Cross-platform Sudoku for Android and Web from a single codebase, using React Native + react-native-web and Expo Router file-based navigation.\n\nCustom 2D canvas rendering via @shopify/react-native-skia replaces React Native Views — GPU-accelerated drawing with zero layout overhead per cell tap. Reanimated 4 and Gesture Handler power smooth cell animations.\n\nPuzzle generation moved off-device: a Node.js script pre-generates a bundled JSON bank at build time, cutting cold-start from 3–11 s to near-instant. MMKV replaces AsyncStorage for offline-first persistence (synchronous reads, ~10× faster). Zustand v5 manages puzzle, settings, and achievements state.\n\nEAS Build pipeline produces Android release APKs with OTA update support via expo-updates. Haptic feedback and audio via expo-haptics and expo-audio. Monetised with AdMob. TypeScript 6 throughout with Jest + jest-expo test suite covering game logic.",
    tech: ["React Native", "TypeScript", "Expo Router", "Zustand", "MMKV", "Skia Canvas", "Reanimated 4", "Gesture Handler", "AdMob"],
    techGroups: [
      { label: "Platform", items: ["React Native", "Expo SDK 56", "TypeScript", "React 19", "Expo Router"] },
      { label: "State & Storage", items: ["Zustand", "react-native-mmkv"] },
      { label: "UI & Animation", items: ["Skia Canvas (GPU rendering)", "Reanimated 4", "Gesture Handler", "Expo Haptics", "Expo Audio"] },
      { label: "Monetisation", items: ["AdMob (react-native-google-mobile-ads)"] },
    ],
    year: "2025",
    gh: "#",
    live: "https://sudoku.binishanaga.com.np/",
    mobile: "http://downloads.binishanaga.com.np/sudoku.apk",
  },
  {
    id: 3,
    name: "Chess",
    tagline: "Cross-platform chess app with AI & multiplayer",
    logo: "/chess.png",
    platforms: ["Web", "Android"],
    desc: "Cross-platform chess app from a single codebase — all game logic, UI, and animations shared across platforms. Four modes: local pass-and-play with Fischer clocks, vs AI (8 difficulty levels via on-device Stockfish native FFI with softmax temperature sampling reaching ~400 Elo), 29-lesson interactive learn mode, and real-time online multiplayer.\n\nServerless AWS backend: AppSync GraphQL + WebSocket subscriptions, 14 Lambda functions for server-authoritative move validation, DynamoDB, and Cognito guest auth. Optimistic UI for online moves with server reconciliation and clean rollback on rejection.\n\nFull in-game action suite: resign, draw offers, takeback requests, rematch. In-game coach with real-time eval bar, blunder detection, hints, and post-game per-move quality grading (brilliant → blunder) with accuracy score. 50+ unit tests covering game logic and online state machine using in-memory fakes.",
    tech: ["Flutter", "Dart", "AWS AppSync", "AWS Lambda", "DynamoDB", "Cognito", "Riverpod", "Stockfish", "WebSocket"],
    year: "2024",
    gh: "#",
    live: "https://chess.binishanaga.com.np/",
    mobile: "http://downloads.binishanaga.com.np/chess.apk",
  },
  {
    id: 4,
    name: "Linear App Clone",
    tagline: "Faithful recreation of Linear's landing page",
    logo: "/linearlogo.png",
    desc: "A pixel-faithful recreation of the Linear project management landing page, built to practice advanced CSS techniques, animation, and responsive design with React and Tailwind CSS.",
    tech: ["React", "TypeScript", "Tailwind CSS"],
    year: "2023",
    gh: "#",
    live: "https://linearclonebini.netlify.app/",
  },
  

];

export const EXPERIENCES = [
  {
    role: "Full Stack Developer",
    company: "Blys",
    period: "June 2025 — Present",
    desc: "Building and maintaining full-stack features across web and mobile platforms.",
  },
  {
    role: "Full Stack Engineer",
    company: "Dhimay Tech",
    period: "July 2024 — May 2025",
    desc: "Developed scalable web applications and APIs, collaborated across the full product lifecycle.",
  },
];

export const CONTACT_LINKS = [
  {
    label: "Email",
    sub: "binisha4200@gmail.com",
    href: "mailto:binisha4200@gmail.com",
    icon: "https://cdn.simpleicons.org/gmail/8a8f98",
  },
  {
    label: "GitHub",
    sub: "Binisha1",
    href: "https://github.com/Binisha1",
    icon: "https://cdn.simpleicons.org/github/8a8f98",
  },
  {
    label: "LinkedIn",
    sub: "binisha-naga",
    href: "https://www.linkedin.com/in/binisha-naga-ab93b1294/",
    icon: null,
  },
  {
    label: "Resume",
    sub: "Download PDF",
    href: "/binisha-resume.pdf",
    icon: null,
    download: true,
  },
];
